# Jobalytics Keywords - Exact copy from extension

general_keywords = [
  ".net",
  ".net developer",
  "37 signals",
  "5g",
  "a/b email test",
  "a/b test",
  "aaa",
  "ab testing",
  "abap",
  "abcl",
  "abuse",
  "acceptance criteria",
  "accessibility",
  "accessibility techniques",
  "account manager",
  "account optimization",
  "account strategies",
  "account strategy",
  "account-level risks",
  "accounting",
  "acl",
  "acquisition",
  "action reviews",
  "actionscript",
  "activemq",
  "ad features",
  "ad technology",
  "ad-hoc",
  "ada",
  "adaptive autosar",
  "adas sw system",
  "adas/ad feature",
  "ado.net",
  "adobe aem",
  "adobe analytics",
  "adobe creative cloud",
  "adobe creative suite",
  "adobe illustrator",
  "adobe photoshop",
  "adobe powerbi",
  "adobe suite",
  "adtech",
  "advanced analytics",
  "advanced analytics platforms",
  "advanced analytics solutions",
  "advertising campaign management",
  "advertising campaigns",
  "advertising performance metrics",
  "advertising proposals",
  "advertising strategy",
  "advising clients",
  "advocacy",
  "afnix",
  "agile",
  "agile methodologies",
  "agile methods",
  "agile planning",
  "agile scrum team",
  "agile software development",
  "agile tools and processes",
  "agile work processes and tools",
  "agilescrum sprint events and cycles",
  "agora",
  "aha",
  "ai",
  "airflow",
  "ajax",
  "alf",
  "algol",
  "algolia",
  "algorithm design",
  "algorithm development",
  "algorithms",
  "alice",
  "alpine",
  "amazon web services",
  "amplitude",
  "analysis",
  "analytic capabilities",
  "analytic tool",
  "analytical",
  "analytical and problem",
  "analytical capabilities",
  "analytical problem-solving",
  "analytical skills",
  "analytical support",
  "analytical tools and techniques",
  "analytics",
  "analytics products",
  "anaplan",
  "android",
  "android developer",
  "angular",
  "angularjs",
  "annotated comps",
  "ansible",
  "anycast",
  "apache",
  "apache airflow",
  "apache camel",
  "apache druid",
  "apache flink",
  "apache kafka",
  "apache solr",
  "apache spark",
  "apex",
  "api",
  "api's",
  "apigee",
  "apl",
  "apollo",
  "app design",
  "app security",
  "applescript",
  "application",
  "application code",
  "application developer",
  "application development",
  "application layer protocol",
  "application scaling",
  "application security engineer",
  "apty",
  "architectural direction",
  "architectural video presentations",
  "architecture",
  "arduino",
  "art direction",
  "artificial intelligence",
  "asana",
  "ascii encoding",
  "asio",
  "asp",
  "asp.net",
  "aspice",
  "assembly",
  "asynchronous systems",
  "atlassian",
  "attention to detail",
  "autoit",
  "automate processes",
  "automate reporting",
  "automated ci/cd",
  "automated testing",
  "automated tests",
  "automating asset inspections processes",
  "automation of processes",
  "automation solutions",
  "automotive adas",
  "automotive adas customer features",
  "automotive camera based adas",
  "automotive code",
  "automotive component",
  "automotive logistics",
  "automotive supplier interaction",
  "autopilot",
  "awk",
  "aws",
  "aws kinesis",
  "aws redshift",
  "aws solutions architect",
  "azure",
  "azuredb",
  "b2b",
  "b2b product solutions",
  "b2b technology",
  "b2c",
  "b2g",
  "babel",
  "back end",
  "back-end",
  "back-end data display",
  "back-end framework",
  "back-end programming language",
  "backbone",
  "backbone.js",
  "backend",
  "backlog",
  "balsamiq",
  "bar membership",
  "base sas",
  "basecamp",
  "bash",
  "basic",
  "batch data",
  "batch data ingestion",
  "batch process",
  "bazel",
  "bbc basic",
  "bdd",
  "beam",
  "beanshell",
  "best practices",
  "beta",
  "bgp",
  "biddable auction advertising",
  "big customer problems",
  "big data",
  "big data technologies",
  "bigquery",
  "bing",
  "bing ads",
  "bioinformatics",
  "bitbucket",
  "blazor",
  "bliss",
  "blockchain",
  "blockchain developer",
  "blue yonder",
  "bootstrap",
  "books",
  "breakdown complex problems",
  "brightedge",
  "browserify",
  "bsd",
  "btravis ci",
  "buffer",
  "bugzilla",
  "build solutions",
  "building codes and standards",
  "business administration",
  "business analysis",
  "business and customer facing",
  "business case",
  "business case development",
  "business growth",
  "business intelligence",
  "business intelligence technologies",
  "business judgment",
  "business management",
  "business models",
  "business objectives",
  "business operation analytics",
  "business performance",
  "business process analysis",
  "business processes",
  "business reports",
  "business reviews",
  "business strategies",
  "business strategy",
  "c",
  "c#",
  "c# developer",
  "c++",
  "c/c++",
  "caching",
  "cakephp",
  "campaign creation",
  "campaign management",
  "campaign optimizations",
  "campaign performance",
  "campaign plans",
  "canva",
  "cascading style sheets",
  "cassandra",
  "ccpa",
  "cdn",
  "cecil",
  "centos",
  "cgi",
  "change management",
  "change management programs",
  "charity",
  "chart.js",
  "chatbot",
  "chromium",
  "chuck",
  "chyrp",
  "ci/cd",
  "cicd",
  "cifs and citrix",
  "cilk",
  "circle",
  "circleci",
  "classification",
  "clean",
  "cleaning procedures",
  "cleo",
  "cli",
  "client acquisition",
  "client facing",
  "client satisfaction",
  "clist",
  "clojure",
  "cloud",
  "cloud app adoption",
  "cloud computing",
  "cloud data services",
  "cloud infrastructure",
  "cloudformation",
  "cloudfront",
  "cloudsearch",
  "cloudwatch",
  "clustering",
  "cms",
  "cnc programmer",
  "cobol",
  "cobra",
  "cocoa",
  "code review",
  "codeigniter",
  "codepipeline",
  "codeship",
  "coding",
  "coldfusion",
  "collaborate",
  "collaborate with back-end developers",
  "collaborate with web designers",
  "collaboration",
  "collaborative",
  "command line",
  "commercial operations",
  "communicate",
  "communication",
  "communication skills",
  "competitive analysis",
  "compiler",
  "complex issues",
  "complex projects",
  "complex systems",
  "compliance",
  "component libraries",
  "component pascal",
  "computational analytics",
  "computer architecture",
  "computer engineer",
  "computer programmer",
  "computer science",
  "computer security",
  "computer vision",
  "computer vision models",
  "concept diagrams",
  "concur",
  "concurrent pascal",
  "conflict resolution",
  "confluence",
  "conjoint",
  "connectivity technologies",
  "consultative",
  "consulting",
  "consumer",
  "consumer behavior principles",
  "consumer decision frameworks",
  "consumer products",
  "consumer psychology",
  "containerization",
  "content creation",
  "content development",
  "content management",
  "content management system",
  "content marketing",
  "contentful",
  "contingency plan",
  "continuous deployment",
  "continuous improvement",
  "continuous improvement activities",
  "continuous integration",
  "continuous integration and deployment",
  "continuous learning",
  "contract management",
  "contractual agreements",
  "conversion",
  "conversion rate optimization",
  "cookies",
  "copywriting",
  "coral",
  "corba",
  "correction protocol",
  "couchdb",
  "coupa",
  "cpq",
  "create processes",
  "create report",
  "create web pages",
  "creative production",
  "critical analysis",
  "critical thinking",
  "crm",
  "crm pipeline",
  "cronjobs",
  "cross functional",
  "cross functional collaboration",
  "cross-browser compatibility",
  "cross-functional",
  "cross-functional collaboration",
  "cross-functionally",
  "cross-sell path",
  "crypto",
  "cryptocurrency",
  "css",
  "css3",
  "csv",
  "cte",
  "cuda",
  "curl",
  "current web trends",
  "curry",
  "customer analysis",
  "customer analytics",
  "customer demographic",
  "customer empathy",
  "customer engagement",
  "customer features",
  "customer journey",
  "customer needs",
  "customer oriented",
  "customer service",
  "customer stories",
  "customer success",
  "customer success metrics",
  "customer surveys",
  "customer value",
  "customer-facing marketing tools",
  "cypress",
  "cypress.io",
  "dal",
  "dap",
  "dart",
  "dash",
  "dashboard specifications",
  "dasl",
  "data",
  "data analysis",
  "data analytics",
  "data and analysis",
  "data consolidation",
  "data driven",
  "data driven decisions",
  "data driven solutions",
  "data engineer",
  "data ingestion",
  "data lake",
  "data mining",
  "data modeling",
  "data models",
  "data pipeline",
  "data platform",
  "data presentation",
  "data processing",
  "data reporting",
  "data science",
  "data sets",
  "data sheets",
  "data solutions",
  "data storytelling",
  "data strategy",
  "data structure",
  "data studio",
  "data validation exercises",
  "data visualization",
  "data visualization tools",
  "data warehouse",
  "data-driven",
  "data-driven analysis",
  "data-driven approach",
  "data-driven metrics",
  "data-informed techniques",
  "data-powered products",
  "database",
  "database administration",
  "database architecture",
  "databricks",
  "datadog",
  "dataflow",
  "dataflow/beam",
  "dataproc",
  "dataset",
  "ddd",
  "dds",
  "debian",
  "debugger",
  "debugging",
  "decision making",
  "decision trees",
  "decision-making",
  "deductive reasoning",
  "deep learning",
  "delphi",
  "demand fulfillment",
  "demand generation",
  "deployment",
  "descriptive / predictive models",
  "descriptive and predictive models",
  "descriptive models",
  "descriptive/predictive models",
  "design",
  "design guides and prototypes",
  "design patterns",
  "design review",
  "design tools and workflows",
  "desktop and mobile app frameworks",
  "detail oriented",
  "detail-oriented",
  "developer relations",
  "development",
  "development life cycle",
  "device drivers",
  "devops",
  "devops practices",
  "dhcp",
  "dibol",
  "digital adoption platform",
  "digital campaigns",
  "digital content",
  "digital marketing",
  "digital products",
  "digital strategy",
  "digital transformation program",
  "digital-minded",
  "direct mail marketing",
  "director of engineering",
  "discovery",
  "discovery assumption mapping",
  "distributed and parallel systems",
  "distributed applications",
  "distributed products",
  "distributed storage",
  "distributed system",
  "distribution channels",
  "distribution strategy",
  "django",
  "dns",
  "dns routing",
  "docker",
  "docker-compose",
  "documentation",
  "docusign",
  "dom",
  "domo",
  "doubleclick",
  "dpdk",
  "draft contacts",
  "dreamweaver",
  "drive revenue",
  "drools",
  "drupal",
  "dtls",
  "dynamic web page design",
  "dynamically-generated segments",
  "dynamo db",
  "dynamodb",
  "e-commerce",
  "early employee",
  "early stage startups",
  "easy-to-understand concepts",
  "easymock",
  "ebpf",
  "ebpf/xdp",
  "ec2",
  "econometric modeling",
  "ecs",
  "eecs",
  "eiffel",
  "elasticache",
  "elasticsearch",
  "elementor",
  "elixir",
  "eloqua",
  "elt",
  "email campaigns",
  "email marketing",
  "embedded language",
  "embedded networking",
  "embedded software engineer",
  "embedded software testing",
  "embedded systems",
  "ember",
  "ember.js",
  "emerging/ground-breaking technologies",
  "enablement framework",
  "end to end process",
  "end-to-end",
  "engineer",
  "enterprise",
  "enterprise saas",
  "enterprise software",
  "enterprise software startup",
  "enterprise solutions",
  "entrepreneur",
  "entrepreneurial",
  "entrepreneurship",
  "enzyme",
  "erlang",
  "erlang and elixir",
  "error detection",
  "es6",
  "ethernet",
  "ethics",
  "etl",
  "etl data",
  "etl data integration",
  "evaluate risks",
  "event budget tracker",
  "event marketing",
  "evergreen campaigns",
  "excel",
  "excel / spreadsheet",
  "execution",
  "experiment",
  "experimental design",
  "experimental test",
  "express",
  "ext.js",
  "extreme programming",
  "f#",
  "f-script",
  "facebook",
  "facebook ads",
  "facebook ads manager",
  "falcon",
  "fast paced environment",
  "fast-growing",
  "fast-paced",
  "feature backlog",
  "feature delivery and tradeoffs",
  "feature roadmapping",
  "feedback",
  "ffmpeg",
  "figma",
  "finance",
  "financial analysis",
  "financial planning",
  "financialforce",
  "fintech",
  "firebase",
  "firefox",
  "firewall",
  "firmware",
  "flask",
  "flexbox",
  "flink",
  "flow",
  "flux",
  "fmp4",
  "forecasting",
  "forth",
  "fortran",
  "founder",
  "framework templates",
  "fraud detection",
  "fraud detection model",
  "fril",
  "frink",
  "front end",
  "front end design",
  "front end technologies",
  "front-end",
  "front-end development",
  "front-end systems",
  "front-end web technologies",
  "frontend",
  "ftp",
  "full stack",
  "full stack software engineer",
  "full-stack",
  "full-stack software engineering",
  "functional programing",
  "functional programming",
  "functional qa",
  "funnel",
  "fusion",
  "game developer",
  "gaming",
  "gant chart",
  "gate",
  "gcp",
  "gcs",
  "generating pipeline",
  "gimp",
  "git",
  "github",
  "gitlab",
  "global design system",
  "gnustep",
  "go",
  "go to market",
  "go-to-market",
  "go-to-market strategy",
  "goal oriented",
  "gocd",
  "golang",
  "google ads",
  "google analytics",
  "google bigquery",
  "google cloud",
  "google cloud platform",
  "google cloud storage",
  "google data studio",
  "google suite",
  "google tag manager",
  "google workspace",
  "googleadobe analytics",
  "gpu",
  "grape",
  "graphic design",
  "graphics design",
  "graphql",
  "gre",
  "grid edge technologies",
  "groovy",
  "group working session",
  "growth",
  "growth and lifecycle marketing",
  "growth hacker",
  "growth marketing strategy",
  "growth strategy",
  "grunt",
  "gstreamer",
  "gsuite",
  "gtm",
  "gtm programs",
  "gtm strategy",
  "guava",
  "guice",
  "gulp",
  "hadoop",
  "hardware",
  "haskell",
  "hbase",
  "hci",
  "heap analytics",
  "heap dump analysis",
  "hellosign integration ecosystem",
  "helm",
  "heroku",
  "high availability",
  "hive",
  "hls",
  "hootsuite",
  "hos",
  "hosting environment",
  "html",
  "html5",
  "html5 app",
  "http",
  "http headers",
  "http methods",
  "http payloads",
  "http response codes",
  "hubspot",
  "human centered design",
  "hypertalk",
  "hypothesis driven outcomes",
  "iaas",
  "ice",
  "ici",
  "icmp",
  "iconography",
  "ide",
  "identity typography",
  "idl",
  "ike",
  "illustrator",
  "imagemagick",
  "implement",
  "implementing digital marketing strategies",
  "inductive reasoning",
  "industry trends",
  "infoblox",
  "informatica intelligent cloud services",
  "information system",
  "information technology",
  "informing standards",
  "infrastructure",
  "infrastructure-as-code",
  "innovation",
  "innovative",
  "instagram",
  "instapage",
  "integration",
  "integration test",
  "inter-related technologies",
  "interaction patterns",
  "interaction standards",
  "interactive tools",
  "intercal",
  "interface",
  "interior design or architecture",
  "interpersonal skills",
  "interviews",
  "inventory control",
  "inventory selections",
  "inventory stocking procedures",
  "investment banking",
  "invision",
  "io",
  "ios developer",
  "iot",
  "ip",
  "ip creation/tracking",
  "ip forwarding",
  "ip management",
  "ipam",
  "ipsec",
  "ipv4/ipv6",
  "ipv6",
  "iso 26262",
  "issues",
  "it operations",
  "iterative development",
  "iterative development process",
  "iterative user research",
  "j2ee",
  "janus",
  "jasmine",
  "jass",
  "java",
  "java developer",
  "java enterprise edition",
  "javascript",
  "javascript developer",
  "javascript/es6",
  "jboss",
  "jenkins",
  "jest",
  "jetson",
  "jetty",
  "jinja2",
  "jira",
  "joomla",
  "joule",
  "jovial",
  "joy",
  "jquery",
  "js",
  "json",
  "jsp",
  "jsunit",
  "junit",
  "jupyter notebook",
  "jvm",
  "kafka",
  "kanban",
  "kensho",
  "keras",
  "kernel",
  "key accounts",
  "key buyer personas",
  "key customer benefits",
  "key customer programs",
  "key performance indicators",
  "key performance metrics",
  "keyword research",
  "keyword targeting",
  "keyword/audience research",
  "kinesis",
  "kissmetrics",
  "kite",
  "komodo",
  "komodo healthcare map",
  "komodo's data and algorithms",
  "kotlin",
  "kpi",
  "kpi metrics",
  "kube flow",
  "kubeflow",
  "kubernetes",
  "labview",
  "laddering techniques",
  "laddering technqiues",
  "lada",
  "lambda",
  "lamp",
  "landing page optimization",
  "laravel",
  "latency",
  "lava",
  "law degree",
  "ldap",
  "lead nurturing",
  "leadership",
  "lean",
  "lean experiments",
  "lean startup",
  "leda",
  "legal",
  "legal advice",
  "legal research",
  "less",
  "li",
  "lifecycle marketing",
  "lifecyle",
  "lightning",
  "limbo",
  "linked lists",
  "linkedin",
  "linkedin ads",
  "linux",
  "linux kernel",
  "linux programming",
  "linux/unix",
  "lisaac",
  "lisp",
  "load changes",
  "lob",
  "logging",
  "logistics management",
  "logo",
  "logo design",
  "lookr",
  "lookup",
  "ltm",
  "ltv",
  "lua",
  "lucene",
  "lv.2/3/4 ad systems",
  "machine learning",
  "machine learning algorithm",
  "machine learning engineer",
  "machine learning languages and packages",
  "machine learning model",
  "macos",
  "mailchimp",
  "maker language",
  "manage accounts",
  "manage monthly budget",
  "manage monthly budget of $xx",
  "mandriva linux",
  "mantisbt",
  "map reduce",
  "mapreduce",
  "market",
  "market & competitive analysis",
  "market analysis",
  "market research",
  "market research & analysis",
  "market segmentation",
  "market trends",
  "marketing automation",
  "marketing automation workflows",
  "marketing campaigns",
  "marketing design",
  "marketing funnel management",
  "marketing management",
  "marketing mix models",
  "marketing operations",
  "marketing planning",
  "marketing plans",
  "marketing technology",
  "marketing technology solutions",
  "marketo",
  "martech",
  "matlab",
  "maven",
  "mdn",
  "media analytics",
  "media management",
  "memcache",
  "merchandising",
  "mercurial",
  "metadata management",
  "metaquotes language",
  "metrics",
  "mfa",
  "micro strategy",
  "micro-services",
  "microservices",
  "microsoft asp.net",
  "microsoft excel",
  "microsoft office",
  "microsoft office applications",
  "microsoft project",
  "microsoft technologies",
  "middleware systems",
  "migration",
  "minimal viable product",
  "miro",
  "misra",
  "mixpanel",
  "ml",
  "ml model",
  "mobile app",
  "mobile development",
  "mobile game development",
  "mobile marketing",
  "mobile software development",
  "mobile technologies",
  "mobile web",
  "mobx",
  "mocha",
  "mock-ups",
  "mockito",
  "mockups",
  "mode",
  "modelling",
  "modern web standard",
  "modula-2",
  "modula-3",
  "moment.js",
  "mondrian",
  "mongo",
  "mongo db",
  "mongodb",
  "monitoring",
  "montoring regulations",
  "moo",
  "motivation theory",
  "moto",
  "mpi",
  "mq",
  "mql",
  "ms access",
  "ms excel",
  "ms office",
  "ms power bi",
  "ms powerpoint",
  "ms windows",
  "ms word",
  "ms-dos",
  "ms-windows",
  "msxml",
  "mulesoft developer",
  "multi-stage projects",
  "multi-tasking capabilities",
  "multi-tenant",
  "multi-threaded",
  "multichanneldigital marketing",
  "multimodal interactions",
  "multitask",
  "multivariate regression",
  "mural",
  "mvc",
  "mvp",
  "mvvm",
  "mysql",
  "nat",
  "natural language processing",
  "ncurses",
  "negotiate agreements",
  "nemerle",
  "neo4j",
  "netcdf",
  "netsuite",
  "netty",
  "network and information security",
  "network engineer",
  "network programming",
  "network/socket",
  "networking",
  "neural network",
  "new product marketing",
  "nginx",
  "nlp",
  "node",
  "node.js",
  "nodejs",
  "non-relational databases",
  "nosql",
  "npm",
  "numpy",
  "nxt-g",
  "oauth",
  "oauth2",
  "oberon",
  "object oriented",
  "object-oriented",
  "object-oriented design",
  "object-oriented programming",
  "object-z",
  "objective c",
  "objective-c",
  "obliq",
  "ocaml",
  "occam",
  "odata",
  "oidc",
  "okrs",
  "okrs pirate metrics",
  "olap",
  "oop",
  "opal",
  "open source",
  "opencl",
  "opencv",
  "opengl",
  "openid",
  "openshift",
  "openssl",
  "operating systems",
  "operational improvements",
  "operational metrics",
  "ops",
  "ops5",
  "opsgenie",
  "optics",
  "optimization",
  "optimizely",
  "optimizers",
  "oracle",
  "oracle developer",
  "oracle sql developer",
  "oral and written communication",
  "organizational ability",
  "organizational skills",
  "orm",
  "os development",
  "ospf",
  "out-of-the-box brand building",
  "oxygene",
  "oz",
  "p4 language",
  "paas",
  "paid search",
  "paid social",
  "paid social media advertising",
  "pandas",
  "pantheon",
  "parallelization",
  "parcel",
  "pardot",
  "parquet",
  "parsers",
  "pascal",
  "passport.js",
  "pcastl",
  "pendo",
  "pentaho",
  "people analytics",
  "people management",
  "performance",
  "performance dashboards",
  "performance improvement",
  "performance metrics",
  "performance testing",
  "performance validation",
  "perl",
  "photoshop",
  "php",
  "php developer",
  "phprojekt",
  "phpunit",
  "pict",
  "pig",
  "piktochart",
  "pinterest",
  "pipeline",
  "pipeline analysis",
  "pitching",
  "pivot table",
  "pl/c",
  "pl/i",
  "pl/sql",
  "platform services",
  "platform tools",
  "play framework",
  "playbook",
  "playwright",
  "pliant",
  "plotly dash",
  "pmbok",
  "pmp",
  "point cloud processing",
  "policy development",
  "poplog",
  "positive reviews",
  "post-launch optimizations",
  "postcss",
  "postgres",
  "postgresql",
  "postscript",
  "powerpoint",
  "powershell",
  "ppc",
  "practical a/b testing",
  "prds",
  "prediction algorithms",
  "predictive intelligence",
  "predictive model",
  "press page",
  "presto",
  "pricing",
  "pricing frameworks",
  "pricing strategies",
  "primary contact",
  "privacy protections",
  "probabilistic filters",
  "probability",
  "problem",
  "problem solving skills",
  "problem-solving",
  "process analysis",
  "process improvement",
  "process management",
  "process optimization",
  "product",
  "product analytics",
  "product and release planning sessions",
  "product delivery",
  "product demonstration",
  "product demos",
  "product design",
  "product development process",
  "product ecosystem",
  "product enhancement",
  "product expert",
  "product features",
  "product implementation",
  "product improvements",
  "product launch",
  "product launch plan",
  "product life-cycle",
  "product lifecycle",
  "product management",
  "product manager",
  "product marketing",
  "product or program management",
  "product pipeline",
  "product pipeline management",
  "product requirement document",
  "product specs",
  "product usage models",
  "product ux",
  "product vision",
  "product vision and strategy",
  "product-oriented quantitative analysis",
  "production agencyvendor management",
  "production defects",
  "professional affairs",
  "program management",
  "program planning",
  "programmer analyst",
  "programming",
  "programming language",
  "programming systems engineering",
  "prograph",
  "project manageer",
  "project management",
  "project management tools",
  "project plans",
  "project risks",
  "project/release management",
  "prolog",
  "propensity modeling",
  "propensity models",
  "protobuf",
  "prototype",
  "prototype system",
  "prototyping",
  "proxy",
  "public relations",
  "pubsub",
  "pulumi",
  "puppet",
  "puppeteer",
  "pure data",
  "pyspark",
  "python",
  "python developer",
  "pytorch",
  "q",
  "qa",
  "qa engineer",
  "qa metrics",
  "qai",
  "qlik",
  "qos",
  "quality assurance",
  "quality production",
  "quality system",
  "quantitative",
  "quantitative analysis",
  "quantitative model",
  "query",
  "query language",
  "qunit",
  "r",
  "r&d",
  "rabbit mq",
  "rabbitmq",
  "radio access networks",
  "rails",
  "rapid prototyping",
  "rapidweaver",
  "rapira",
  "raspberry pi",
  "ravendb",
  "rds",
  "react",
  "react developer",
  "react native",
  "react.js",
  "reactjs",
  "reactnative",
  "real time",
  "real-time",
  "real-time analysis",
  "realm mobile database",
  "realtime",
  "rebol",
  "recommendations",
  "redis",
  "redshift",
  "reduced cpa/cpl",
  "redux",
  "regex",
  "regression",
  "regulatory",
  "relational database",
  "relationship management",
  "release",
  "release criteria and management",
  "release infrastructure",
  "release management",
  "relevant demographic specialization",
  "reliability",
  "report automation",
  "report templates",
  "requirements analysis",
  "requirements gathering",
  "research",
  "research and development",
  "resolve dependencies",
  "responsive",
  "responsive application",
  "responsive design",
  "responsive development",
  "rest",
  "rest apis",
  "rest applications",
  "restapi",
  "restful",
  "restful api",
  "restlet",
  "results-oriented",
  "retail sales process",
  "retail tech",
  "revenue analysis",
  "revenue growth",
  "revenue impact",
  "revenue quota",
  "revolution",
  "rexx",
  "rfp",
  "rfp process",
  "rhel",
  "risk management",
  "roa",
  "roadmap",
  "roadmap planning",
  "roadmap strategy",
  "roadmunk",
  "robotics engineer",
  "robots",
  "roi",
  "role-based access",
  "roop",
  "root cause analysis",
  "ros",
  "routing",
  "routing protocol",
  "rpg",
  "rspec",
  "ruby",
  "ruby on rails",
  "rust",
  "s-lang",
  "s-plus",
  "s3",
  "saas",
  "saas attribution modeling",
  "saas models outcome-based models",
  "saas product",
  "saas sale",
  "sales",
  "sales and marketing",
  "sales communications",
  "sales enablement assets",
  "sales pipeline",
  "sales tools",
  "salesforce",
  "salesforce app exchange",
  "salesforce crm",
  "salesforce developer",
  "salsa",
  "saml",
  "saml integrations",
  "sap",
  "sas",
  "sas macros",
  "sas stat",
  "sass/less",
  "scala",
  "scalability",
  "scalable",
  "scalable processes",
  "schema",
  "scientific computing",
  "scikit learn",
  "scikit-learn",
  "scikitlearn",
  "scipy",
  "scope",
  "scripting",
  "scrum",
  "scrum ceremonies",
  "scrum methodologies",
  "scrum processes",
  "scss",
  "sdk",
  "sdlc",
  "search and social",
  "search engine marketing",
  "search engine optimization",
  "search processing",
  "seasonal campaigns",
  "security",
  "security compliance",
  "sed",
  "segment",
  "segmentation",
  "selenium",
  "self",
  "self-motivate",
  "self-serve channels",
  "self-starter",
  "sell your ideas",
  "sem",
  "sensor calibration",
  "seo",
  "sequential and multi-armed bandit",
  "server-side scripting",
  "serverless",
  "service delivery",
  "service desk",
  "service level agreements",
  "service management products",
  "service production marketing technology",
  "service roadmap",
  "sftp",
  "sgml",
  "sharepoint developer",
  "shell",
  "shell script",
  "ship",
  "signal processing",
  "simula",
  "simulink",
  "sip",
  "site reliability",
  "sketch",
  "sklearn",
  "sla",
  "slack",
  "slate",
  "slideshare",
  "slo",
  "small",
  "smalltalk",
  "smb google workspace",
  "smb google workspace strategy",
  "sme capacity",
  "smil",
  "snmp",
  "snobol",
  "snowflake",
  "sns",
  "soap",
  "social & mobile applications",
  "social distancing guidelines",
  "social media",
  "social media apps",
  "social media marketing",
  "social media metrics",
  "social media platforms",
  "social media software",
  "social studio",
  "software",
  "software + hardware",
  "software architecture",
  "software developer",
  "software development",
  "software development life cycle",
  "software development lifecycle",
  "software development roadmap",
  "software engineer",
  "software sales",
  "software security",
  "software stacks",
  "software workflow",
  "software-as-as-service",
  "software-defined networking",
  "solaris/aix",
  "sold channels",
  "solidity",
  "solr",
  "solutions",
  "soluton briefs",
  "sonarqube",
  "soql/sosl",
  "sorting algorithms",
  "sound legal judgment",
  "source / version control",
  "source code",
  "spam",
  "spark",
  "specification",
  "specification development",
  "spin",
  "spl2",
  "splunk",
  "spring",
  "spring boot",
  "spring cloud",
  "spring data",
  "spring framework",
  "spring mvc",
  "sprint",
  "sprint planning",
  "spss",
  "sql",
  "sql developer",
  "sql server",
  "sql-like scripting language",
  "sqlalchemy",
  "sqlite",
  "sqs",
  "squirrel scripting",
  "sr",
  "sr management",
  "sre",
  "ssh",
  "ssi",
  "ssl",
  "sso",
  "stage gate process",
  "stakeholders",
  "standard business processes",
  "standard practices",
  "startup",
  "stata",
  "state management",
  "statistical methodologies",
  "statistical methods",
  "statistical modeling",
  "statistical packages",
  "statistics",
  "status",
  "step functions",
  "storage systems and management",
  "storybook",
  "strategic",
  "strategic growth projects",
  "strategic learning management system",
  "strategic planning",
  "strategic projects",
  "strategy",
  "stream data",
  "streaming",
  "stress tolerance",
  "structural layouts",
  "styling and color design",
  "subscription management",
  "subscription video service",
  "subversion",
  "success metrics",
  "suitescript",
  "supervised",
  "supervised learning",
  "svn",
  "sw production release",
  "swagger",
  "swift",
  "switching",
  "swot analysis",
  "symfony",
  "syslog",
  "system integration",
  "systemc",
  "tableau",
  "target segments",
  "task automation",
  "task management",
  "tcl",
  "tcl/tk",
  "tcp",
  "tcp/ip",
  "tdd",
  "teamwork",
  "tech stack",
  "tech support",
  "technical",
  "technical architecture",
  "technical documentation",
  "technical functionality",
  "technical implementation methods",
  "technical product management",
  "technical reporting",
  "technology trends and architectures",
  "telemarketing",
  "tensorflow",
  "tentpole",
  "teradata",
  "terraform",
  "test & quality",
  "test automation",
  "test development",
  "test driven development",
  "test infrastructure",
  "test plan",
  "test planning",
  "test strategies",
  "test-driven development",
  "test-driven-development",
  "testing",
  "tex and latex",
  "thread dump analysis",
  "time management",
  "timeline planning",
  "tls",
  "tms",
  "tomcat",
  "tooling development",
  "top-tier management",
  "tradeshows",
  "transactions",
  "travis",
  "travis ci",
  "travisci",
  "trello",
  "trend analysis",
  "triage issues",
  "troubleshooting",
  "troubleshooting/debugging",
  "tsql",
  "tuning",
  "tunneling",
  "turing",
  "twilio",
  "twitter",
  "twitter ads",
  "tws",
  "typescript",
  "typical design tools",
  "typography",
  "uat",
  "ubuntu",
  "udp",
  "ui",
  "ui design and development",
  "ui developer",
  "ui engineering",
  "ui standards",
  "ui toolkits and frameworks",
  "ui/ux",
  "umbraco",
  "unbounce",
  "unified modeling language",
  "unit and integration testing",
  "unit test",
  "unity developer",
  "unix",
  "unix programming",
  "unix shell",
  "unsupervised",
  "unsupervised learning",
  "upsell & cross sell",
  "uptime",
  "url",
  "usability",
  "usability studies",
  "use cases",
  "user centric",
  "user design",
  "user empathy",
  "user experience",
  "user features",
  "user feedback",
  "user interaction",
  "user interaction design",
  "user interface",
  "user interface design",
  "user persona",
  "user requirements",
  "user research",
  "user scenarios",
  "user stories",
  "user story writing",
  "user test",
  "user testing plans",
  "user testing sessions",
  "user-centered",
  "user-centered design",
  "user-centered design techniques",
  "ux",
  "ux design",
  "ux design methodologies",
  "ux design principles",
  "ux design processes",
  "ux patterns",
  "ux research methods",
  "ux vision & strategy",
  "ux/design language style libraries",
  "ux/ui",
  "validate",
  "validation",
  "vanilla js",
  "vbscript",
  "vendor management",
  "vendoragency management",
  "venture capital",
  "verbal communication skills",
  "verilog",
  "version control",
  "version control system",
  "version repository",
  "vertica",
  "vertx",
  "vhdl",
  "vi",
  "video editing",
  "video marketing",
  "video production",
  "vim/vi",
  "vision",
  "visual basic",
  "visual brand",
  "visual design",
  "visual foxpro",
  "visual studio",
  "visualforce",
  "visualization software",
  "vlan",
  "vpn",
  "vrfs",
  "vrml",
  "vrrp",
  "vue",
  "vue.js",
  "vuejs",
  "walkme",
  "wap",
  "wap/wml",
  "wcag",
  "wcag 2.1 compliance standards",
  "wcf",
  "weave flux",
  "web",
  "web accessibility",
  "web accessibility standards.understanding",
  "web api",
  "web app",
  "web application",
  "web application development",
  "web architecture",
  "web based software applications",
  "web design",
  "web developer",
  "web development",
  "web hosting",
  "web infrastructure",
  "web performance",
  "web production",
  "web projects",
  "web rollout",
  "web security",
  "web services",
  "web site",
  "web site registration",
  "web standards",
  "web technologies",
  "web technologies.experience",
  "web technology",
  "web3",
  "webdriverio",
  "webkit",
  "webpack",
  "webrtc",
  "website application",
  "website content display",
  "website development",
  "website hosting",
  "website infrastructure",
  "website management tools",
  "website navigation optimization",
  "website performance",
  "website performance optimization",
  "website technology",
  "websockets",
  "whatfix",
  "whitepapers",
  "windows powershell",
  "wireframe",
  "wireframing",
  "wml",
  "wms",
  "wordpress",
  "wordpress developer",
  "work collaboratively",
  "wpf",
  "writing",
  "writing modules",
  "written",
  "wsdl",
  "wsgi",
  "xaml",
  "xaraya",
  "xdp",
  "xhtml",
  "xl",
  "xl deploy",
  "xml",
  "xotcl",
  "xpath",
  "xsl",
  "xslt",
  "yaml",
  "yarn",
  "youtube",
  "yui",
  "zendesk",
  "zeromq",
  "zikula",
  "zuora"
]

swe_essentials = [
  ".net",
  ".net developer",
  "actionscript",
  "ado.net",
  "ai",
  "airflow",
  "ajax",
  "alpine",
  "amazon web services",
  "android developer",
  "angular",
  "angularjs",
  "apache",
  "apache airflow",
  "apache camel",
  "apache druid",
  "apache flink",
  "apache kafka",
  "apache solr",
  "apache spark",
  "apex",
  "api",
  "apigee",
  "apollo",
  "applescript",
  "application developer",
  "application layer protocol",
  "application security engineer",
  "arduino",
  "artificial intelligence",
  "asp",
  "asp.net",
  "assembly",
  "aws",
  "aws kinesis",
  "aws redshift",
  "aws solutions architect",
  "azure",
  "babel",
  "back end",
  "back-end",
  "backbone",
  "backbone.js",
  "backend",
  "bash",
  "bbc basic",
  "bdd",
  "bgp",
  "big data",
  "bigquery",
  "blockchain",
  "blockchain developer",
  "blue yonder",
  "bsd",
  "bugzilla",
  "c",
  "c#",
  "c# developer",
  "c++",
  "cakephp",
  "cascading style sheets",
  "centos",
  "chart.js",
  "ci/cd",
  "circle",
  "clojure",
  "cloud",
  "cloud app adoption",
  "cloud computing",
  "cloud infrastructure",
  "cloudformation",
  "cms",
  "cnc programmer",
  "cobol",
  "cobra",
  "cocoa",
  "codeigniter",
  "codepipeline",
  "coldfusion",
  "collaboration",
  "collaborative",
  "command line",
  "communication",
  "communicative",
  "compiler",
  "component libraries",
  "component pascal",
  "computer architecture",
  "computer engineering",
  "computer programmer",
  "computer science",
  "computer security",
  "computer vision",
  "computer vision models",
  "concur",
  "concurrent pascal",
  "content management system",
  "cookies",
  "coral",
  "corba",
  "couchdb",
  "cronjobs",
  "cryptocurrency",
  "css",
  "cte",
  "cuda",
  "curl",
  "curry",
  "cypress",
  "dal",
  "dap",
  "dart",
  "dasl",
  "data engineer",
  "database",
  "database administration",
  "database architecture",
  "ddd",
  "debian",
  "decision-making",
  "deep learning",
  "delphi",
  "dhcp",
  "dibol",
  "director of engineering",
  "distributed system",
  "django",
  "dpdk",
  "drools",
  "drupal",
  "dtls",
  "dynamo db",
  "dynamodb",
  "ebpf",
  "ec2",
  "ecs",
  "eiffel",
  "elasticache",
  "elasticsearch",
  "elixir",
  "elt",
  "embedded software engineer",
  "erlang",
  "es6",
  "ext.js",
  "f#",
  "f-script",
  "ffmpeg",
  "firebase",
  "firewall",
  "flask",
  "flink",
  "flux",
  "forth",
  "fortran",
  "fril",
  "frink",
  "front end",
  "front-end",
  "frontend",
  "ftp",
  "full stack",
  "full-stack",
  "game developer",
  "gcp",
  "gcs",
  "git",
  "go",
  "golang",
  "google bigquery",
  "google cloud",
  "google cloud platform",
  "google cloud storage",
  "google tag manager",
  "gpu",
  "grape",
  "graphql",
  "gre",
  "groovy",
  "grunt",
  "gstreamer",
  "guava",
  "guice",
  "gulp",
  "hadoop",
  "haskell",
  "hbase",
  "hci",
  "hive",
  "hos",
  "html",
  "html5",
  "hypertalk",
  "ice",
  "ici",
  "icmp",
  "idl",
  "ike",
  "imagemagick",
  "information system",
  "information technology",
  "intercal",
  "io",
  "ios developer",
  "ip",
  "ipam",
  "ipsec",
  "ipv4/ipv6",
  "iso 26262",
  "jasmine",
  "jass",
  "java",
  "java developer",
  "java enterprise edition",
  "javascript",
  "javascript developer",
  "jboss",
  "jenkins",
  "jest",
  "jetson",
  "jetty",
  "jinja2",
  "joomla",
  "jquery",
  "js",
  "json",
  "kafka",
  "kinesis",
  "kotlin",
  "kubernetes",
  "labview",
  "lambda",
  "lamp",
  "laravel",
  "lava",
  "ldap",
  "li",
  "lightning",
  "linux",
  "linux kernel",
  "linux programming",
  "linux/unix",
  "lisp",
  "lua",
  "machine learning",
  "machine learning engineer",
  "macos",
  "maker language",
  "mandriva linux",
  "mantisbt",
  "maven",
  "memcache",
  "mercurial",
  "metaquotes language",
  "misra",
  "ml",
  "ml model",
  "mobx",
  "moment.js",
  "mongo",
  "mongo db",
  "mongodb",
  "mq",
  "ms-dos",
  "ms-windows",
  "msxml",
  "mulesoft developer",
  "multi-threaded",
  "mvc",
  "mvvm",
  "mysql",
  "nat",
  "natural language processing",
  "nemerle",
  "netcdf",
  "netty",
  "network and information security",
  "network engineer",
  "network programming",
  "networking",
  "nginx",
  "nlp",
  "node",
  "node.js",
  "nodejs",
  "non-relational databases",
  "nosql",
  "npm",
  "numpy",
  "oauth",
  "oauth2",
  "objective c",
  "objective-c",
  "ocaml",
  "odata",
  "oidc",
  "opencl",
  "opengl",
  "openid",
  "openssl",
  "operating systems",
  "optimizely",
  "oracle developer",
  "oracle sql developer",
  "orm",
  "os development",
  "ospf",
  "pandas",
  "parquet",
  "parsers",
  "pascal",
  "passport.js",
  "pentaho",
  "performance testing",
  "perl",
  "php",
  "php developer",
  "phpunit",
  "pl/i",
  "pl/sql",
  "play framework",
  "playwright",
  "postcss",
  "postgres",
  "postgresql",
  "postgressql",
  "postscript",
  "powershell",
  "presto",
  "problem-solving",
  "programmer analyst",
  "prolog",
  "protobuf",
  "puppeteer",
  "pyspark",
  "python",
  "python developer",
  "pytorch",
  "qa engineer",
  "r",
  "rabbit mq",
  "rabbitmq",
  "rails",
  "raspberry pi",
  "ravendb",
  "react",
  "react developer",
  "react native",
  "react.js",
  "reactjs",
  "reactnative",
  "redis",
  "redshift",
  "redux",
  "regex",
  "relational database",
  "responsive",
  "responsive design",
  "responsive development",
  "rest",
  "rest applications",
  "restapi",
  "restful api",
  "restlet",
  "rexx",
  "rhel",
  "robotics engineer",
  "rpg",
  "ruby",
  "ruby on rails",
  "rust",
  "s-plus",
  "s3",
  "salesforce developer",
  "saml",
  "sas",
  "scala",
  "scikit learn",
  "scikit-learn",
  "scikitlearn",
  "scipy",
  "search engine optimization",
  "security compliance",
  "sed",
  "selenium",
  "sensor calibration",
  "seo",
  "sftp",
  "sgml",
  "sharepoint developer",
  "shell script",
  "simula",
  "simulink",
  "sketch",
  "sklearn",
  "smalltalk",
  "smil",
  "snmp",
  "sns",
  "soap",
  "software developer",
  "software engineer",
  "solaris/aix",
  "sonarqube",
  "soql/sosl",
  "spark",
  "spl2",
  "splunk",
  "spring",
  "spring boot",
  "spring cloud",
  "spring mvc",
  "spss",
  "sql",
  "sql developer",
  "sqlalchemy",
  "sqlite",
  "sqs",
  "squirrel scripting",
  "ssh",
  "ssi",
  "ssl",
  "stata",
  "step functions",
  "storybook",
  "subversion",
  "suitescript",
  "svn",
  "swift",
  "symfony",
  "syslog",
  "tcl",
  "tcl/tk",
  "tcp",
  "tcp/ip",
  "tdd",
  "teamwork",
  "tensorflow",
  "teradata",
  "terraform",
  "tls",
  "tms",
  "tomcat",
  "travis",
  "travis ci",
  "travisci",
  "tsql",
  "tunneling",
  "typescript",
  "ubuntu",
  "udp",
  "ui",
  "ui developer",
  "ui/ux",
  "umbraco",
  "unified modeling language",
  "unity developer",
  "unix",
  "ux",
  "ux/ui",
  "vbscript",
  "vertica",
  "vertx",
  "vhdl",
  "visual basic",
  "visual foxpro",
  "visualforce",
  "vlan",
  "vpn",
  "vrfs",
  "vrrp",
  "vue",
  "vue.js",
  "vuejs",
  "wap",
  "wap/wml",
  "wcf",
  "web developer",
  "webkit",
  "webpack",
  "webrtc",
  "websockets",
  "wml",
  "wms",
  "wordpress",
  "wordpress developer",
  "wpf",
  "wsdl",
  "wsgi",
  "xaml",
  "xdp",
  "xhtml",
  "xml",
  "xpath",
  "xsl",
  "xslt",
  "yarn",
  "yui"
]

swe_nice_to_haves = [
  "5g",
  "a/b test",
  "ab testing",
  "ad features",
  "ad technology",
  "adobe aem",
  "adobe analytics",
  "adobe powerbi",
  "adtech",
  "advanced analytics",
  "advanced analytics platforms",
  "advanced analytics solutions",
  "advertising performance metrics",
  "afnix",
  "agile",
  "agora",
  "airflow",
  "algolia",
  "algorithm design",
  "algorithm development",
  "algorithms",
  "amplitude",
  "analytic capabilities",
  "ansible",
  "anycast",
  "app security",
  "application scaling",
  "asana",
  "ascii encoding",
  "asynchronous systems",
  "atlassian",
  "automate processes",
  "automate reporting",
  "automated ci/cd",
  "automated testing",
  "automated tests",
  "automating asset inspections processes",
  "automation of processes",
  "automation solutions",
  "automotive adas",
  "automotive adas customer features",
  "automotive camera based adas",
  "automotive code",
  "automotive component",
  "automotive logistics",
  "automotive supplier interaction",
  "b2b product solutions",
  "b2b technology",
  "batch data ingestion",
  "beam",
  "bgp",
  "bitbucket",
  "blazor",
  "bliss",
  "bootstrap",
  "browserify",
  "chromium",
  "classification",
  "clustering",
  "code review",
  "competitive analysis",
  "compliance",
  "concept diagrams",
  "confluence",
  "connectivity technologies",
  "containerization",
  "continuous improvement",
  "continuous improvement activities",
  "continuous integration",
  "continuous integration and deployment",
  "continuous learning",
  "correction protocol",
  "crm",
  "crm pipeline",
  "cross-browser compatibility",
  "csv",
  "dash",
  "datadog",
  "dataflow",
  "debugging",
  "decision trees",
  "descriptive and predictive models",
  "descriptive models",
  "descriptive/predictive models",
  "devops",
  "dhcp",
  "discovery assumption mapping",
  "distributed and parallel systems",
  "distributed applications",
  "distributed products",
  "distributed storage",
  "dns",
  "docker",
  "docker-compose",
  "dom",
  "domo",
  "dreamweaver",
  "e-commerce",
  "easymock",
  "econometric modeling",
  "embedded language",
  "embedded networking",
  "embedded software testing",
  "embedded systems",
  "entrepreneurial",
  "ethernet",
  "etl",
  "etl data",
  "etl data integration",
  "excel",
  "ffmpeg",
  "figma",
  "financialforce",
  "fintech",
  "firefox",
  "fmp4",
  "framework templates",
  "fraud detection",
  "fraud detection model",
  "functional qa",
  "funnel",
  "fusion",
  "generating pipeline",
  "github",
  "gitlab",
  "gnustep",
  "google analytics",
  "google suite",
  "gtm",
  "helm",
  "heroku",
  "hls",
  "hubspot",
  "iaas",
  "iconography",
  "illustrator",
  "infoblox",
  "invision",
  "jira",
  "jsunit",
  "junit",
  "jupyter notebook",
  "kanban",
  "keras",
  "kernel",
  "kube flow",
  "kubeflow",
  "laddering techniques",
  "ltm",
  "lucene",
  "matlab",
  "mdn",
  "micro-services",
  "microservices",
  "miro",
  "mixpanel",
  "mocha",
  "mockito",
  "motivation theory",
  "mpi",
  "ms access",
  "ms power bi",
  "multivariate regression",
  "network/socket",
  "neural network",
  "olap",
  "opencv",
  "openshift",
  "opsgenie",
  "organizational ability",
  "parallelization",
  "pendo",
  "performance improvement",
  "performance metrics",
  "photoshop",
  "phprojekt",
  "pig",
  "piktochart",
  "pipeline",
  "pmbok",
  "point cloud processing",
  "prediction algorithms",
  "predictive models",
  "privacy protections",
  "probabilistic filters",
  "process improvement",
  "product analytics",
  "product design",
  "project management",
  "pubsub",
  "pulumi",
  "puppet",
  "qos",
  "quantitative analysis",
  "quantitative model",
  "qunit",
  "radio access networks",
  "rapid prototyping",
  "rapidweaver",
  "report automation",
  "report templates",
  "roadmap planning",
  "roadmap strategy",
  "roadmunk",
  "ros",
  "s-lang",
  "salesforce crm",
  "sap",
  "scrum",
  "selenium",
  "sgml",
  "signal processing",
  "sip",
  "sketch",
  "slideshare",
  "software architecture",
  "software security",
  "solr",
  "sorting algorithms",
  "spark",
  "splunk",
  "statistical methods",
  "statistical modeling",
  "statistical packages",
  "statistics",
  "strategic planning",
  "supervised learning",
  "system integration",
  "systemc",
  "technical documentation",
  "tensorflow",
  "terraform",
  "test automation",
  "test development",
  "test driven development",
  "test infrastructure",
  "test-driven development",
  "test-driven-development",
  "testing",
  "tex and latex",
  "trello",
  "twilio",
  "tws",
  "typography",
  "uat",
  "unit test",
  "unix shell",
  "unsupervised learning",
  "user test",
  "verilog",
  "vhdl",
  "vi",
  "vim/vi",
  "visual studio",
  "visualization software",
  "vrrp",
  "walkme",
  "wcag",
  "weave flux",
  "web security",
  "webdriverio",
  "webkit",
  "whatfix",
  "xl deploy",
  "zikula"
]

pm_marketing_keywords = [
  ".net",
  "a/b email test",
  "a/b test",
  "acceptance criteria",
  "account optimization",
  "accounting",
  "acquisition",
  "ad-hoc",
  "adobe creative cloud",
  "adobe creative suite",
  "adobe illustrator",
  "adobe photoshop",
  "adobe powerbi",
  "adobe suite",
  "adtech",
  "advertising campaign management",
  "advertising campaigns",
  "advertising proposals",
  "advertising strategy",
  "agile",
  "aha",
  "analytical",
  "analytical skills",
  "android",
  "angular",
  "api",
  "application developer",
  "art direction",
  "asana",
  "automation tools",
  "autopilot",
  "aws",
  "azure",
  "azuredb",
  "b2b",
  "b2b technology",
  "b2c",
  "b2g",
  "babel",
  "backend",
  "backlog",
  "balsamiq",
  "base sas",
  "basecamp",
  "batch data",
  "bing",
  "bing ads",
  "bootstrap",
  "brand management",
  "breakdown complex problems",
  "brightedge",
  "browserify",
  "btravis ci",
  "buffer",
  "business administration",
  "business case",
  "business reports",
  "business strategy",
  "campaign creation",
  "campaign management",
  "campaign plans",
  "canva",
  "chart.js",
  "client acquisition",
  "cloud data services",
  "cloud infrastructure",
  "clustering",
  "cms",
  "commercial operations",
  "communication skills",
  "communications",
  "competitive analysis",
  "complex systems",
  "conflict resolution",
  "confluence",
  "conjoint",
  "consulting",
  "consumer",
  "consumer decision frameworks",
  "consumer products",
  "consumer psychology",
  "content development",
  "content marketing",
  "conversion",
  "copywriting",
  "create report",
  "creative production",
  "critical analysis",
  "critical thinking",
  "crm",
  "cross-functional",
  "cross-sell path",
  "css",
  "customer analysis",
  "customer empathy",
  "customer engagement",
  "customer journey",
  "customer needs",
  "customer oriented",
  "customer success",
  "customer surveys",
  "customer value",
  "customer-facing marketing tools",
  "data",
  "data analysis",
  "data analytics",
  "data science",
  "data studio",
  "data visualization",
  "data-driven",
  "database",
  "decision making",
  "decision trees",
  "decision-making",
  "demand generation",
  "design",
  "detail-oriented",
  "developer relations",
  "digital campaigns",
  "digital marketing",
  "digital-minded",
  "direct mail marketing",
  "discovery",
  "distributed products",
  "distributed system",
  "distribution channels",
  "distribution strategy",
  "django",
  "docusign",
  "domo",
  "doubleclick",
  "drupal",
  "early employee",
  "early stage startups",
  "eloqua",
  "email campaigns",
  "email marketing",
  "end-to-end",
  "engineer",
  "enterprise",
  "enterprise saas",
  "enterprise software",
  "entrepreneurial",
  "entrepreneurship",
  "etl",
  "evaluate risks",
  "event budget tracker",
  "event marketing",
  "evergreen campaigns",
  "excel",
  "excel / spreadsheet",
  "execution",
  "experimental test",
  "extreme programming",
  "facebook",
  "facebook ads",
  "facebook ads manager",
  "fast-growing",
  "fast-paced",
  "feedback",
  "finance",
  "financial planning",
  "firebase",
  "flexbox",
  "forecasting",
  "founder",
  "funnel",
  "gaming",
  "gant chart",
  "git",
  "github",
  "go to market",
  "go-to-market",
  "go-to-market strategy",
  "goal oriented",
  "google ads",
  "google analytics",
  "google data studio",
  "google tag manager",
  "graphic design",
  "graphql",
  "group working session",
  "growth",
  "growth and lifecycle marketing",
  "growth hacker",
  "growth marketing strategy",
  "gtm",
  "gtm strategy",
  "hadoop",
  "heap analytics",
  "heap dump analysis",
  "high availability",
  "hive",
  "hootsuite",
  "html",
  "html5",
  "html5 app",
  "hubspot",
  "ide",
  "implementing digital marketing strategies",
  "industry trends",
  "informatica intelligent cloud services",
  "instagram",
  "instapage",
  "integrations",
  "interactive tools",
  "interviews",
  "inventory control",
  "inventory selections",
  "investment banking",
  "invision",
  "ios",
  "it operations",
  "java",
  "java enterprise edition",
  "javascript",
  "jira",
  "jquery",
  "kensho",
  "key buyer personas",
  "key customer benefits",
  "keyword research",
  "keyword targeting",
  "keyword/audience research",
  "kissmetrics",
  "kpi",
  "laddering technqiues",
  "landing page optimization",
  "lead nurturing",
  "lean",
  "lean startup",
  "legal",
  "lifecycle marketing",
  "linkedin",
  "linkedin ads",
  "lob",
  "logo design",
  "lookr",
  "ltv",
  "machine learning",
  "mailchimp",
  "manage monthly budget",
  "mapreduce",
  "market",
  "market analysis",
  "market research",
  "market research & analysis",
  "market segmentation",
  "market trends",
  "marketing automation",
  "marketing automation workflows",
  "marketing campaigns",
  "marketing funnel management",
  "marketing management",
  "marketing mix models",
  "marketing planning",
  "marketo",
  "martech",
  "merchandising",
  "metadata management",
  "microsoft office",
  "minimal viable product",
  "mixpanel",
  "mobile app",
  "mobile marketing",
  "mobile web",
  "mockups",
  "modelling",
  "motivation theory",
  "mql",
  "ms word",
  "multivariate regression",
  "mvp",
  "mysql",
  "new product marketing",
  "node",
  "operating systems",
  "ops",
  "optimizely",
  "oracle",
  "organizational ability",
  "organizational skills",
  "out-of-the-box brand building",
  "paid search",
  "paid social",
  "paid social media advertising",
  "pardot",
  "performance",
  "php",
  "pig",
  "piktochart",
  "pinterest",
  "pitching",
  "platform services",
  "playbook",
  "powerpoint",
  "ppc",
  "prds",
  "pricing",
  "pricing frameworks",
  "pricing strategies",
  "problem",
  "product",
  "product design",
  "product ecosystem",
  "product implementation",
  "product launch",
  "product lifecycle",
  "product management",
  "product manager",
  "product marketing",
  "product requirement document",
  "product specs",
  "product vision",
  "professional affairs",
  "project management",
  "public relations",
  "python",
  "qa",
  "quality assurance",
  "quantitative",
  "quantitative model",
  "query language",
  "r&d",
  "rails",
  "react",
  "reactnative",
  "realm mobile database",
  "reduced cpa/cpl",
  "regulatory",
  "release",
  "relevant demographic specialization",
  "reliability",
  "requirements analysis",
  "requirements gathering",
  "research",
  "research and development",
  "resolve dependencies",
  "results-oriented",
  "retail tech",
  "revenue growth",
  "revenue impact",
  "roa",
  "roadmap",
  "roadmunk",
  "roi",
  "ruby",
  "rust",
  "saas",
  "saas attribution modeling",
  "sales",
  "sales and marketing",
  "sales enablement assets",
  "salesforce",
  "sas macros",
  "sas stat",
  "sass",
  "scala",
  "scalability",
  "scope",
  "scripting",
  "scrum",
  "sdlc",
  "search and social",
  "search engine marketing",
  "search engine optimization",
  "search processing",
  "seasonal campaigns",
  "segmentation",
  "segments",
  "self-motivate",
  "self-serve channels",
  "self-starter",
  "sell your ideas",
  "sem",
  "seo",
  "ship",
  "sketch",
  "slack",
  "slideshare",
  "sme capacity",
  "social media",
  "social media marketing",
  "social media metrics",
  "social media platforms",
  "social studio",
  "software",
  "software development",
  "software development lifecycle",
  "software engineering",
  "sold channels",
  "soluton briefs",
  "spark",
  "specification",
  "sprint",
  "spss",
  "sql",
  "sre",
  "stakeholders",
  "startup",
  "status",
  "strategy",
  "stream data",
  "success metrics",
  "swift",
  "swot analysis",
  "tableau",
  "target segments",
  "technical",
  "technical architecture",
  "technical documentation",
  "telemarketing",
  "tentpole",
  "teradata",
  "testing",
  "thread dump analysis",
  "tradeshows",
  "trello",
  "triage issues",
  "tsql",
  "twilio",
  "twitter",
  "twitter ads",
  "typescript",
  "ui",
  "unbounce",
  "usability",
  "use cases",
  "user centric",
  "user empathy",
  "user experience",
  "user persona",
  "user requirements",
  "user research",
  "user stories",
  "user test",
  "user-centered",
  "user-centered design",
  "ux design",
  "ux/ui",
  "validate",
  "vendor management",
  "venture capital",
  "verbal communication skills",
  "video editing",
  "video marketing",
  "video production",
  "vision",
  "vue.js",
  "web design",
  "webpack",
  "whitepapers",
  "wireframing",
  "wordpress",
  "work collaboratively",
  "written",
  "youtube"
]

synonyms = [
  [
    "machine learning",
    "ml"
  ],
  [
    "ai",
    "artificial intelligence"
  ],
  [
    "engineer",
    "engineering"
  ],
  [
    "user centric",
    "user-centric"
  ],
  [
    "wireframing",
    "wireframes",
    "wireframe",
    "wire frame"
  ],
  [
    "specification",
    "spec",
    "specs",
    "product spec"
  ],
  [
    "detail-oriented",
    "detail oriented"
  ],
  [
    "a/b testing",
    "ab test",
    "ab testing",
    "a/b test"
  ],
  [
    "micro-services",
    "microservices"
  ],
  [
    "aws",
    "amazon web services"
  ],
  [
    "backend",
    "back-end",
    "back end"
  ],
  [
    "frontend",
    "front-end",
    "front end"
  ],
  [
    "rest applications",
    "restful api"
  ],
  [
    "spring mvc",
    "spring boot",
    "spring data",
    "spring framework"
  ],
  [
    "gcp",
    "google cloud platform"
  ],
  [
    "object-oriented",
    "object oriented"
  ],
  [
    "test-driven development",
    "tdd",
    "test-driven-development",
    "test driven development"
  ],
  [
    "apache solr",
    "solr"
  ],
  [
    "apache kafka",
    "kafka"
  ],
  [
    "debugger",
    "debugging"
  ],
  [
    "analytics",
    "analysis"
  ],
  [
    "cross-functional",
    "cross-functionally"
  ],
  [
    "google cloud storage",
    "gcs"
  ],
  [
    "real-time",
    "real time",
    "realtime"
  ],
  [
    "reactjs",
    "react.js",
    "react",
    "react js"
  ],
  [
    "vue",
    "vuejs",
    "vue.js"
  ],
  [
    "node.js",
    "nodejs",
    "node"
  ],
  [
    "continuous integration",
    "ci"
  ],
  [
    "postgres",
    "postgresql",
    "postgressql"
  ],
  [
    "cms",
    "content management system"
  ],
  [
    "crm",
    "customer relationship management"
  ],
  [
    "cascading style sheets",
    "css",
    "css3"
  ],
  [
    "ux/ui",
    "ui/ux"
  ],
  [
    "html",
    "html5"
  ],
  [
    "javascript",
    "js"
  ],
  [
    "angular",
    "angularjs",
    "angular.js"
  ]
]
